export const ErrorCode = {
  // Generic
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Claim
  CLAIM_NOT_FOUND: 'CLAIM_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  CLAIM_NOT_EDITABLE: 'CLAIM_NOT_EDITABLE',
  CLAIM_ALREADY_IN_VENDOR_BATCH: 'CLAIM_ALREADY_IN_VENDOR_BATCH',

  // Notification
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ALREADY_USED: 'NOTIFICATION_ALREADY_USED',
  NOTIFICATION_CODE_EXISTS: 'NOTIFICATION_CODE_EXISTS',

  // Vendor
  VENDOR_CODE_EXISTS: 'VENDOR_CODE_EXISTS',
  VENDOR_HAS_DEPENDENCIES: 'VENDOR_HAS_DEPENDENCIES',

  // Photo
  PHOTO_NOT_FOUND: 'PHOTO_NOT_FOUND',
  PHOTO_ALREADY_REVIEWED: 'PHOTO_ALREADY_REVIEWED',
  REQUIRED_PHOTOS_MISSING: 'REQUIRED_PHOTOS_MISSING',

  // Vendor Claim
  VENDOR_CLAIM_NOT_FOUND: 'VENDOR_CLAIM_NOT_FOUND',
  NO_APPROVED_CLAIMS_FOR_BATCH: 'NO_APPROVED_CLAIMS_FOR_BATCH',

  // Master Data
  DEFECT_CODE_EXISTS: 'DEFECT_CODE_EXISTS',
  MODEL_NAME_VENDOR_EXISTS: 'MODEL_NAME_VENDOR_EXISTS',
  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',

  // Settings
  SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED'
} as const

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode]
